Add optional extras stage and update package versions

diff --git a/install b/install
--- a/install
+++ b/install
@@ -18,7 +18,7 @@ BLUE=$'\033[34m'
 MAGENTA=$'\033[35m'
 RESET=$'\033[0m'
 
-OPTSTRING=":Acdfhl:pstv"
+OPTSTRING=":Acdfhl:opstv"
 called_with_args="false"
 PHASE=""
 
@@ -57,7 +57,7 @@ usage() {
     printf 'It can run the full install or individual stages.\n'
     printf 'If a stage fails, troubleshoot it and continue from that point.\n'
     printf '\n'
-    printf 'Usage: %s [-A] [-v] [-h] [-s] [-p] [-d] [-t] [-c] [-l <arg>] [-f] [--version]\n' "$0"
+    printf 'Usage: %s [-A] [-v] [-h] [-s] [-p] [-d] [-t] [-c] [-l <arg>] [-o] [-f] [--version]\n' "$0"
     printf '    -A        :  ALL   :   Complete install including drive partitioning\n'
     printf '    -v        :  DEPS  :   Verify dependencies on host system\n'
     printf '    -h        :  Help  :   Display help message\n'
@@ -68,7 +68,8 @@ usage() {
     printf '    -t        : Step 4 :   Install the toolchain\n'
     printf '    -c        : Step 5 :   Prepare the chroot environment\n'
     printf '    -l <arg>  : Step 6 :   Install LFS phases [1|2|3|4|5|all]\n'
-    printf '    -f        : Step 7 :   Install kernel, config files, and clean up the build system\n'
+    printf '    -o        : Step 7 :   Install cmake, fastfetch, and required dependencies (%sOptional%s)\n' "$BLUE" "$RESET"
+    printf '    -f        : Step 8 :   Install kernel, config files, and clean up the build system\n'
     printf '\n'
     printf '    --version :        :   Display version information\n'
     printf '\n'
@@ -535,10 +536,16 @@ run_all_lfs_phases() {
     graft_install_phase_pkg 2 ncurses 6.6
 
     run_named_phase 3
-    graft_install_phase_pkg 3 perl 5.42.1
+    graft_install_phase_pkg 3 perl 5.42.2
 
     run_named_phase 4
     run_named_phase 5
+}
+
+run_optional_stage() {
+    [ -f "$LFS/lfs-ai/scripts/optional" ] || die "Missing $LFS/lfs-ai/scripts/optional"
+    require_lfs_chroot_env
+    run_in_lfs_chroot /bin/bash /lfs-ai/scripts/optional
 }
 
 run_final_stage() {
@@ -731,6 +738,13 @@ while getopts "$OPTSTRING" opt; do
             export ROOT_PASS
             run_all_lfs_phases
 
+            # Install optional packages
+            if prompt_confirm 'Would you like to install cmake, fastfetch, and required dependencies?'; then
+                run_optional_stage
+            else
+                printf '%sSkipping optional packages.%s\n\n' "$GREEN" "$RESET"
+            fi
+
             # Final setup
             printf '%sInstalling kernel and cleaning up build system.%s\n\n' "$MAGENTA" "$RESET"
 
@@ -903,7 +917,6 @@ while getopts "$OPTSTRING" opt; do
         printf 'If you reboot between install steps the drive name could change as they are not always loaded in the same order.\n'
         printf 'Check %ssettings.conf%s again if a reboot is performed.\n\n' "$BLUE" "$RESET"
 
-
         if prompt_confirm 'Are you ready to continue?'; then
             printf '%sStarting install.%s\n\n' "$GREEN" "$RESET"
 
@@ -953,6 +966,36 @@ while getopts "$OPTSTRING" opt; do
             ;;
 
             esac
+        else
+            exit 1
+        fi
+    ;;
+
+
+    o) # Optional packages
+        called_with_args="true"
+        require_root
+        maybe_clear
+        printf '%sInstalling optional packages.%s\n' "$MAGENTA" "$RESET"
+        printf 'This will install cmake, fastfetch, and required dependencies\n\n'
+
+        printf 'This could be a dangerous operation!\n'
+        printf 'Ensure %sSteps 1-6%s were previously complete.\n\n' "$BLUE" "$RESET"
+
+        printf 'If you reboot between install steps the drive name could change as they are not always loaded in the same order.\n'
+        printf 'Check %ssettings.conf%s again if a reboot is performed.\n\n' "$BLUE" "$RESET"
+
+        if prompt_confirm 'Are you ready to continue?'; then
+            printf '%sStarting install.%s\n\n' "$GREEN" "$RESET"
+
+            load_config
+
+            printf '%sVerify mounts...%s\n' "$MAGENTA" "$RESET"
+            ensure_build_mounts
+            ensure_chroot_mounts
+            printf '%sVerification successful!%s\n\n' "$GREEN" "$RESET"
+
+            run_optional_stage
         else
             exit 1
         fi
diff --git a/optional/01-libxml2 b/optional/01-libxml2
--- a/optional/01-libxml2
+++ b/optional/01-libxml2
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
-# LFS-AI - Build and install Xml parser
+# LFS-AI - Build and install libxml2
 # Copyright (c) 2026 Michael Femiak (Vercety1534)
 # SPDX-License-Identifier: MIT
 
 set -euo pipefail
 
-PACKAGE=XML-Parser
-VERSION=2.55
+PACKAGE=libxml2
+VERSION=2.15.2
 
 RED=$'\033[31m'
 GREEN=$'\033[32m'
@@ -23,7 +23,7 @@ die() {
 
 
 # Log command
-LOG_FILE="/logs/lfs/phase4/$PACKAGE-$VERSION.log"
+LOG_FILE="/logs/optional/$PACKAGE-$VERSION.log"
 
 run_log() {
     if "$@" >> "$LOG_FILE" 2>&1; then
@@ -35,24 +35,35 @@ run_log() {
 }
 
 
-[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.gz"
+[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.xz"
 
 cd /sources
 
 rm -rf "$PACKAGE-$VERSION"
-tar -xf "$PACKAGE-$VERSION.tar.gz"
+tar -xf "$PACKAGE-$VERSION.tar.xz"
 cd "/sources/$PACKAGE-$VERSION"
 
 printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
-run_log perl Makefile.PL
+sed -i "/'git'/,+3d" meson.build
+
+mkdir -p build
+cd       build
+
+run_log meson setup ..            \
+              --prefix=/usr       \
+              --buildtype=release \
+              -D history=enabled  \
+              -D icu=enabled
 printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"
 
 printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
-run_log make
+run_log ninja
 printf '%sBuild successful!%s\n' "$GREEN" "$RESET"
 
 printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
-run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install
+run_log env DESTDIR="/usr/pkg/$PACKAGE/$VERSION" ninja install
+
+sed "s/--static/--shared/" -i "/usr/pkg/$PACKAGE/$VERSION/usr/bin/xml2-config"
 printf '%sPackage successful!%s\n' "$GREEN" "$RESET"
 
 printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
diff --git a/optional/02-nghttp2 b/optional/02-nghttp2
--- a/optional/02-nghttp2
+++ b/optional/02-nghttp2
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
-# LFS-AI - Build and install Xml parser
+# LFS-AI - Build and install nghttp2
 # Copyright (c) 2026 Michael Femiak (Vercety1534)
 # SPDX-License-Identifier: MIT
 
 set -euo pipefail
 
-PACKAGE=XML-Parser
-VERSION=2.55
+PACKAGE=nghttp2
+VERSION=1.68.1
 
 RED=$'\033[31m'
 GREEN=$'\033[32m'
@@ -23,7 +23,7 @@ die() {
 
 
 # Log command
-LOG_FILE="/logs/lfs/phase4/$PACKAGE-$VERSION.log"
+LOG_FILE="/logs/optional/$PACKAGE-$VERSION.log"
 
 run_log() {
     if "$@" >> "$LOG_FILE" 2>&1; then
@@ -35,16 +35,18 @@ run_log() {
 }
 
 
-[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.gz"
+[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.xz"
 
 cd /sources
 
 rm -rf "$PACKAGE-$VERSION"
-tar -xf "$PACKAGE-$VERSION.tar.gz"
+tar -xf "$PACKAGE-$VERSION.tar.xz"
 cd "/sources/$PACKAGE-$VERSION"
 
 printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
-run_log perl Makefile.PL
+run_log ./configure --prefix=/usr     \
+                    --enable-lib-only \
+                    --docdir="/usr/share/doc/$PACKAGE-$VERSION"
 printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"
 
 printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
diff --git a/optional/03-libuv b/optional/03-libuv
--- a/optional/03-libuv
+++ b/optional/03-libuv
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
-# LFS-AI - Build and install Xml parser
+# LFS-AI - Build and install libuv
 # Copyright (c) 2026 Michael Femiak (Vercety1534)
 # SPDX-License-Identifier: MIT
 
 set -euo pipefail
 
-PACKAGE=XML-Parser
-VERSION=2.55
+PACKAGE=libuv
+VERSION=1.52.1
 
 RED=$'\033[31m'
 GREEN=$'\033[32m'
@@ -23,7 +23,7 @@ die() {
 
 
 # Log command
-LOG_FILE="/logs/lfs/phase4/$PACKAGE-$VERSION.log"
+LOG_FILE="/logs/optional/$PACKAGE-$VERSION.log"
 
 run_log() {
     if "$@" >> "$LOG_FILE" 2>&1; then
@@ -35,16 +35,17 @@ run_log() {
 }
 
 
-[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.gz"
+[ -f "/sources/$PACKAGE-v$VERSION.tar.gz" ] || die "Missing source archive: /sources/$PACKAGE-v$VERSION.tar.gz"
 
 cd /sources
 
-rm -rf "$PACKAGE-$VERSION"
-tar -xf "$PACKAGE-$VERSION.tar.gz"
-cd "/sources/$PACKAGE-$VERSION"
+rm -rf "$PACKAGE-v$VERSION"
+tar -xf "$PACKAGE-v$VERSION.tar.gz"
+cd "/sources/$PACKAGE-v$VERSION"
 
 printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
-run_log perl Makefile.PL
+run_log sh autogen.sh
+run_log ./configure --prefix=/usr
 printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"
 
 printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
@@ -61,4 +62,4 @@ run_log graft -iV "$PACKAGE/$VERSION"
 printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"
 
 cd /sources
-rm -rf "$PACKAGE-$VERSION"
+rm -rf "$PACKAGE-v$VERSION"
diff --git a/optional/06-curl b/optional/06-curl
--- a/optional/06-curl
+++ b/optional/06-curl
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
-# LFS-AI - Build and install Xml parser
+# LFS-AI - Build and install curl
 # Copyright (c) 2026 Michael Femiak (Vercety1534)
 # SPDX-License-Identifier: MIT
 
 set -euo pipefail
 
-PACKAGE=XML-Parser
-VERSION=2.55
+PACKAGE=curl
+VERSION=8.19.0
 
 RED=$'\033[31m'
 GREEN=$'\033[32m'
@@ -23,7 +23,7 @@ die() {
 
 
 # Log command
-LOG_FILE="/logs/lfs/phase4/$PACKAGE-$VERSION.log"
+LOG_FILE="/logs/optional/$PACKAGE-$VERSION.log"
 
 run_log() {
     if "$@" >> "$LOG_FILE" 2>&1; then
@@ -35,16 +35,19 @@ run_log() {
 }
 
 
-[ -f "/sources/$PACKAGE-$VERSION.tar.gz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.gz"
+[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.xz"
 
 cd /sources
 
 rm -rf "$PACKAGE-$VERSION"
-tar -xf "$PACKAGE-$VERSION.tar.gz"
+tar -xf "$PACKAGE-$VERSION.tar.xz"
 cd "/sources/$PACKAGE-$VERSION"
 
 printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
-run_log perl Makefile.PL
+run_log ./configure --prefix=/usr    \
+                    --disable-static \
+                    --with-openssl   \
+                    --with-ca-path=/etc/ssl/certs
 printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"
 
 printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
@@ -53,6 +56,16 @@ printf '%sBuild successful!%s\n' "$GREEN" "$RESET"
 
 printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
 run_log make DESTDIR="/usr/pkg/$PACKAGE/$VERSION" install
+
+run_log rm -rf docs/examples/.deps
+
+run_log find docs \( -name Makefile\* -o  \
+             -name \*.1       -o  \
+             -name \*.3       -o  \
+             -name CMakeLists.txt \) -delete
+
+run_log install -d "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc"
+run_log cp -v -R docs -T "/usr/pkg/$PACKAGE/$VERSION/usr/share/doc/$PACKAGE-$VERSION"
 printf '%sPackage successful!%s\n' "$GREEN" "$RESET"
 
 printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
diff --git a/optional/08-fastfetch b/optional/08-fastfetch
--- a/optional/08-fastfetch
+++ b/optional/08-fastfetch
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
-# LFS-AI - Build and install D bus
+# LFS-AI - Build and install fastfetch
 # Copyright (c) 2026 Michael Femiak (Vercety1534)
 # SPDX-License-Identifier: MIT
 
 set -euo pipefail
 
-PACKAGE=dbus
-VERSION=1.16.2
+PACKAGE=fastfetch
+VERSION=2.61.0
 
 RED=$'\033[31m'
 GREEN=$'\033[32m'
@@ -23,7 +23,7 @@ die() {
 
 
 # Log command
-LOG_FILE="/logs/lfs/phase5/$PACKAGE-$VERSION.log"
+LOG_FILE="/logs/optional/$PACKAGE-$VERSION.log"
 
 run_log() {
     if "$@" >> "$LOG_FILE" 2>&1; then
@@ -35,19 +35,18 @@ run_log() {
 }
 
 
-[ -f "/sources/$PACKAGE-$VERSION.tar.xz" ] || die "Missing source archive: /sources/$PACKAGE-$VERSION.tar.xz"
+[ -f "/sources/$VERSION.tar.gz" ] || die "Missing source archive: /sources/$VERSION.tar.gz"
 
 cd /sources
 
 rm -rf "$PACKAGE-$VERSION"
-tar -xf "$PACKAGE-$VERSION.tar.xz"
+tar -xf "$VERSION.tar.gz"
 cd "/sources/$PACKAGE-$VERSION"
 
-mkdir build
-cd    build
-
 printf '%sConfiguring %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
-run_log meson setup --prefix=/usr --buildtype=release --wrap-mode=nofallback ..
+mkdir -p build
+cd       build
+run_log cmake -DCMAKE_INSTALL_PREFIX=/usr -G Ninja ..
 printf '%sConfiguration successful!%s\n' "$GREEN" "$RESET"
 
 printf '%sBuilding %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
@@ -56,13 +55,51 @@ printf '%sBuild successful!%s\n' "$GREEN" "$RESET"
 
 printf '%sPackaging %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
 run_log env DESTDIR="/usr/pkg/$PACKAGE/$VERSION" ninja install
-
-run_log ln -svf /etc/machine-id "/usr/pkg/$PACKAGE/$VERSION/var/lib/dbus"
 printf '%sPackage successful!%s\n' "$GREEN" "$RESET"
 
 printf '%sInstalling %s...%s\n' "$MAGENTA" "$PACKAGE" "$RESET"
 run_log graft -pDV "$PACKAGE/$VERSION"
 run_log graft -iV "$PACKAGE/$VERSION"
+
+run_log install -d -m755 /etc/skel/.config/fastfetch
+run_log install -d -m755 /root/.config/fastfetch
+
+cat > /etc/skel/.config/fastfetch/config.jsonc <<'EOF'
+{
+  "$schema": "https://github.com/fastfetch-cli/fastfetch/raw/dev/doc/json_schema.json",
+  "logo": {
+    "type": "none"
+  },
+  "display": {
+    "separator": "  "
+  },
+  "modules": [
+    "title",
+    "os",
+    "host",
+    "kernel",
+    "uptime",
+    {
+      "type": "command",
+      "key": "Packages",
+      "text": "find /usr/pkg -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | awk '{print $1}'"
+    },
+    "shell",
+    "terminal",
+    "cpu",
+    "gpu",
+    "memory",
+    {
+      "type": "disk",
+      "folders": "/"
+    },
+    "localip",
+    "colors"
+  ]
+}
+EOF
+
+run_log cp -f /etc/skel/.config/fastfetch/config.jsonc /root/.config/fastfetch/config.jsonc
 printf '%sInstall successful!%s\n\n\n' "$GREEN" "$RESET"
 
 cd /sources
